# Generated by Django 4.0.3 on 2022-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
