# Generated by Django 4.0.3 on 2022-03-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_registermodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='repassword',
        ),
    ]
