# Generated by Django 4.0.3 on 2022-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_registermodel_repassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='reemail',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='rephone',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermodel',
            name='pic',
            field=models.ImageField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='gender',
            field=models.CharField(choices=[['Male', 'MALE'], ['Female', 'FEMALE']], max_length=10),
        ),
    ]
